name: Trigger Netlify Build
on:
  schedule:
    # “At 20:00 on every day-of-week from Monday through Friday.”
    # https://crontab.guru/#0_20_*_*_0-6
    - cron: '0 0-23 * * 0-6'
jobs:
  build:
    name: Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} BUILD_HOOK_URL
